Const KEY_ESCAPE = 1
Const KEY_TAB = 15
Const KEY_ARROW_LEFT = 203
Const KEY_ARROW_RIGHT = 205
Const KEY_ARROW_UP = 200
Const KEY_ARROW_DOWN = 208

Const SCREEN_MODE_DEFAULT = 0
Const SCREEN_MODE_FULLSCREEN = 1
Const SCREEN_MODE_WINDOWED_FIX = 2
Const SCREEN_MODE_WINDOWED_SCALABLE = 3